# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.9.3-1-gab67cf0
_src_path: /var/folders/t6/57q65mk543l7xw6_bdgx1bmc0000gn/T/tmpkn2hrvj7/template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: None
author_name: None
contract_name: hello_world
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: production
project_name: test_smart_contract_generator_default_production_preset_python
python_linter: ruff
use_dispenser: false
use_github_actions: true
use_pre_commit: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

