[algokit]
min_version = "v1.7.3"

[deploy]
command = "npm run deploy:ci"
environment_secrets = [
  "DEPLOYER_MNEMONIC",
]

[deploy.localnet]
environment_secrets = []

[generate.smart_contract]
description = "Adds new smart contract to existing project"
path = ".algokit/generators/create_contract"
