name: Release production_beaker

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate production_beaker
    uses: ./.github/workflows/production-beaker-ci.yaml
  deploy-testnet:
    runs-on: "ubuntu-latest"
    needs: validate
    environment: contract-testnet
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Bootstrap dependencies
        run: algokit bootstrap all --project-name 'production_beaker'

      - name: Configure git
        shell: bash
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Deploy to testnet
        run: algokit deploy testnet --project-name 'production_beaker'
        env:
          # This is the account that becomes the creator of the contract
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          # The dispenser account is used to ensure the deployer account is funded
          DISPENSER_MNEMONIC: ${{ secrets.DISPENSER_MNEMONIC }}
