[algokit]
min_version = "v1.3.0"

[deploy]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = [
  "DEPLOYER_MNEMONIC",
  "DISPENSER_MNEMONIC",
]

[deploy.localnet]
environment_secrets = []
