[algokit]
min_version = "v1.1.0-beta.4"

[deploy]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = []

[deploy.localnet]
environment_secrets = []

[deploy.testnet]
environment_secrets = [
  "DEPLOYER_MNEMONIC",
  "DISPENSER_MNEMONIC"
]
